name: Build & Test

on: push

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Package
      run: |
        python3 -m venv .virtualenv
        . .virtualenv/bin/activate
        pip install -r ci_build_requirements.txt
        python setup.py check
        python -m build

    - name: Publish Package
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
        if-no-files-found: error

  test:
    strategy:
      matrix:
        system:
        - python: '3.12'
          platform: Linux
          runs-on: ubuntu-latest
        - python: '3.12'
          platform: Windows
          runs-on: windows-latest
        - python: '3.11'
          platform: Linux
          runs-on: ubuntu-latest
        - python: '3.11'
          platform: Windows
          runs-on: windows-latest
        - python: '3.10'
          platform: Linux
          runs-on: ubuntu-latest
        - python: '3.10'
          platform: Windows
          runs-on: windows-latest
        - python: '3.9'
          platform: Linux
          runs-on: ubuntu-latest
        - python: '3.9'
          platform: Windows
          runs-on: windows-latest
        - python: '3.8'
          platform: Linux
          runs-on: ubuntu-latest
        - python: '3.8'
          platform: Windows
          runs-on: windows-latest
        - python: '3.7'
          platform: Linux
          runs-on: ubuntu-22.04 # keep limping along so long as GH offers this older image
        - python: '3.7'
          platform: Windows
          runs-on: windows-latest

    name: Test Py ${{ matrix.system.python }} on ${{ matrix.system.platform }}
    runs-on: ${{ matrix.system.runs-on }}
    needs: package
    timeout-minutes: 3

    steps:
    - name: Install Python ${{ matrix.system.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.system.python }}

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Download Packaged Distribution
      uses: actions/download-artifact@v4
      with:
        name: dist

    - name: Test
      run: |
        ${{ (runner.os == 'Windows')
            && '$seano_wheel = Get-ChildItem .\seano_cli-*-py3-*.whl | Select-Object -Expand FullName'
            || 'seano_wheel=seano_cli-*-py3-*.whl' }}
        pip install $seano_wheel -r ci_utest_requirements.txt
        python -m pytest test
